- config/build.ts
- config/deploy.ts
- private-playlists/word.yaml
- private-samples/word/01-basics/basic-api-call.yaml
OfficeJS now has private snippets, which are independent of the old playlists (now treated as 'public') and will not be included as defaults in applications such as Script Lab.
The directory structure remains the same: under `private-samples` choose the appropriate `host`, add a subdirectory denoting what type of snippet it is, and then add the snippet name. A sample Word snippet is included in this pull request.
> Add private OfficeJS snippets

- config/build.ts
- playlists/outlook.yaml
- view/outlook.json
Noticed that npm start was overwriting the custom office.js
> Prevent build.ts from overwriting office.js in outlook snippets

- config/build.ts
- samples/excel/01-basics/basic-api-call-es5.yaml
- samples/excel/01-basics/basic-api-call.yaml
- samples/excel/01-basics/basic-common-api-call.yaml
- samples/excel/default.yaml
- samples/onenote/default.yaml
- samples/outlook/01-compose-basics/get-item-subject.yaml
- samples/outlook/01-compose-basics/get-selected-text.yaml
- samples/outlook/01-compose-basics/set-selected-text.yaml
- samples/powerpoint/basics/basic-common-api-call.yaml
- samples/powerpoint/basics/get-slide-metadata.yaml
- samples/powerpoint/basics/insert-image.yaml
- samples/powerpoint/default.yaml
- samples/project/basics/basic-common-api-call.yaml
- samples/project/default.yaml
- samples/web/default.yaml
- samples/word/01-basics/basic-api-call-es5.yaml
- samples/word/01-basics/basic-api-call.yaml
- samples/word/01-basics/basic-common-api-call.yaml
- samples/word/default.yaml
This is something that's become more and more apparent with folks using non-canonical Office.js (e.g., beta, or unpkg private/alpha versions).  Needing to replace things at 2 different spots in the file is harder than just one place.
I think re-ordering would make it much simpler to do these sorts of changes.
Note that I'm doing this for only a subset of samples for now (all the basic/default one).  Will let someone else go through the rest, though that work is likely just an hour or so (and can be done alongside the other cleanup).  It should essentially be just a copy-paste, making sure to adjust for the few samples that do make use of other libraries.  This remaining cleanup work is tracked as part of https://github.com/OfficeDev/office-js-snippets/issues/81
You can skip over the …
> Moving JS references next to their corresponding d.ts files.

- playlists/word.yaml
- samples/word/50-common-patterns/multiple-property-set.yaml
- view/word.json
Since this snippet does not use any Preview APIs, I made the following changes:
- Set the required requirement set (back) to 1.3.
- Reference the prod Office.js library and prod Office.d.ts (instead of beta).
- Move the snippet (back) into the 50-common-patterns folder.
> Update yaml and folder for multiple-property-set (Word) snippet.

- samples/excel/82-document/get-file-in-slices-async.yaml
The get-file-in-slices-async snippet has an unclear verification instruction involving going to a third-party site. The proposed changes are a solution using the createWorkbook function in preview right now. There's some clunkiness around switching to beta libraries, but it's more manageable than having users create a file from the base64string another way.
> Add Application.createWorkbook as verification to file slicing

- samples/excel/82-document/get-file-in-slices-async.yaml
Here's the email text from Jipeng:
@Alexander Jerabek For the createworkbook API, the context.application.createWorkbook().open(); is not suggested to be used by user.
Instead we have changed to the following way, where can we put the documentation? Thanks.
Excel.createWorkbook(base64).catch(function (error) {
app.showNotification(error.code, error.message);
if (error instanceof OfficeExtension.Error) {
app.showNotification("Debug info: ", JSON.stringify(error.debugInfo));
}
});
> Correcting sample to follow product team guidance

- samples/excel/85-preview-apis/shape-create-and-delete.yaml
- samples/excel/85-preview-apis/shape-move-and-order.yaml
- samples/excel/85-preview-apis/tetrominos.yaml
`addGeomtricShape` no longer takes position and size parameters. Adjusting the snippets accordingly.
Note: There's a bug in the API at the moment around `ShapeFill.foreColor`. That's separate from this issue.
> [excel] (Shapes) Match geometric shape add method to new signature

- config/build.ts
- samples/outlook/01-compose-basics/get-item-subject.yaml
- samples/outlook/01-compose-basics/get-selected-text.yaml
- samples/outlook/01-compose-basics/set-selected-text.yaml
- yarn.lock
The most up-to-date version of office.js no longer contains the bug we were working around, so outlook can start using cannonical js again. This also broke modern script-lab for outlook, so wins on 2 fronts.
> Fix #65 and update snippets accordingly

- samples/word/10-content-controls/insert-and-change-content-controls.yaml
- samples/word/25-paragraph/search.yaml
- snippet-extractor-output/snippets.yaml
Need to load only properties that the code will be **reading**, not those that it will be writing. These snippets read `length` in loops, but they don't read any other properties. The snippets worked before only because if you load _anything_ on a collection type, you get `length` loaded too.
> [Word] (search) fix search snippet to load the correct properties

- samples/excel/85-preview-apis/comment.yaml
- snippet-extractor-output/snippets.yaml
This snippet unintentionally required the user to have cell A1 selected. That has been corrected.
> [excel] (Comments) Make comment snippet more robust

- samples/excel/99-just-for-fun/path-finder-game.yaml
- samples/excel/99-just-for-fun/patterns.yaml
Some worksheet creation methods within the snippets were not properly changed during the recent removal of office-js-helpers. This corrects that mistake.
> excel] (Just for fun) Fixing fun snippets to use proper null checking pattern when creating worksheets

- README.md
Removing the HTML break, as it was breaking the links in the next paragraph.
> [typo] Readme fixes

- samples/excel/44-shape/shape-images.yaml
- samples/excel/50-workbook/create-workbook.yaml
- samples/excel/85-preview-apis/workbook-insert-external-worksheets.yaml
- samples/excel/99-just-for-fun/tetrominos.yaml
- samples/powerpoint/basics/create-presentation.yaml
- snippet-extractor-output/snippets.yaml
This is the snippets repo equivalent for this PR: https://github.com/OfficeDev/office-js-docs-pr/pull/1283.
> [excel, powerpoint] (Create Workbook/Presentation) Update code samples to avoid casting

- samples/excel/42-range/range-find.yaml
- snippet-extractor-output/snippets.yaml
This is to address https://github.com/OfficeDev/office-js-docs-reference/issues/504 downstream. Those variable names should up out of context in the methods when pulled from the snippet.
> [excel] (Range.find) Addressing sample naming for ref doc snippets

- samples/excel/42-range/cell-properties.yaml
- snippet-extractor-output/snippets.yaml
(Based on an [internal work item](https://office.visualstudio.com/OC/_workitems/edit/3467808/))
`SettableCellProperties.style` can only take a limited set of strings: built-in style names and custom style names. This clarifies how to find the built-in names.
> [excel] (CellProperties) Clarifying style input

- config/build.ts
- config/helpers.ts
- package.json
- yarn.lock
This change allows yarn to work with the latest version of node (instead of being limited to 8.11.3).
> [admin] Allowing yarn start to run on later node versions

- samples/excel/42-range/range-copyfrom.yaml
- snippet-extractor-output/snippets.yaml
This helps reduce extra code in the snippets destined for reference docs.
> [excel] (Copy/Paste) Removing autofitColumns calls from copy and move snippets

- samples/excel/90-scenarios/performance-optimization.yaml
- snippet-extractor-output/snippets.yaml
Calling `suspendScreenUpdatingUntilNextSync` in a loop causes the Excel window to flicker. This helps guide customers away from such behavior.
> [excel] (Performance) Adding performance note above suspendScreenUpdatingUntilNextSync

- tslint.json
This removes the "no-use-before-declare is deprecated" warning message when running `yarn start`.
> [admin] Updating linter settings

- samples/excel/42-range/precedents.yaml
Adding back in a tryCatch method that was accidentally deleted in #564.
> [Excel] (Range) Add accidentally deleted tryCatch

- samples/powerpoint/preview-apis/shapes.yaml
Fixes [618](https://github.com/OfficeDev/office-js-snippets/issues/618)
> Fixes instructions in PPT shapes snippet

- playlists-prod/outlook.yaml
- playlists/outlook.yaml
- samples/outlook/20-item-body/add-inline-base64-image.yaml
- view-prod/outlook.json
- view/outlook.json
This snippet will be referenced from [Add and remove attachments in an Outlook add-in](https://docs.microsoft.com/office/dev/add-ins/outlook/add-and-remove-attachments-to-an-item-in-a-compose-form).
> [Outlook] (compose) Snippet to add inline base64 image to message body

- playlists-prod/outlook.yaml
- playlists/outlook.yaml
- samples/outlook/99-preview-apis/get-base64-encoding.yaml
- samples/outlook/99-preview-apis/get-eml-format.yaml
- view-prod/outlook.json
- view/outlook.json
Creates a code snippet for the `getAsFileAsync` method. This snippet will be added to the reference documentation in a separate PR (pending DT PR merge).
Related PRs:
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66028
- https://github.com/OfficeDev/office-js-docs-reference/pull/1634
- https://github.com/OfficeDev/office-js-docs-pr/pull/4102
> [Outlook] (spam reporting) Create snippet for the getAsFileAsync method

- samples/word/50-document/manage-footnotes.yaml
Footnotes feature was released in WordApi 1.5 and so works in additional clients/platforms.
> [Word] (footnotes) Remove online-only restriction

- playlists-prod/excel.yaml
- playlists/excel.yaml
- samples/excel/20-data-types/data-types-error-values.yaml
- snippet-extractor-output/snippets.yaml
This update addresses a customer documentation request by showing how to control the output of a data type cell, if the data type returns as an error. 
Customer request: https://github.com/OfficeDev/Office-Add-in-samples/issues/630
> [Excel] (Data types) Expand functionality of error snippet

- playlists-prod/outlook.yaml
- playlists/outlook.yaml
- samples/outlook/35-notifications/add-getall-remove.yaml
- snippet-extractor-output/snippets.yaml
Fixes the snippet that adds an insight notification to a mail item. The snippet now references command IDs available in the Script Lab manifest. This PR also cleans up the task pane UI to provide users with instructions on how to effectively run the snippet.
> [Outlook] (notifications) Fix insight notification snippet

- playlists-prod/word.yaml
- playlists/word.yaml
- samples/word/90-scenarios/correlated-objects-pattern.yaml
- view-prod/word.json
- view/word.json
[This article](https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/correlated-objects-pattern) has samples that show the benefits of avoiding context.sync calls in a loop. This PR adds the sample for the correlated objects pattern (and the less performant variant). 
Open to feedback on the folder/playlist placement. as well as other notes on the sample code itself.
> [word] (Performance) Add a sample highlighting the perf benefits of the correlated objects pattern

- playlists-prod/outlook.yaml
- playlists/outlook.yaml
- samples/outlook/99-preview-apis/send-async.yaml
- view-prod/outlook.json
- view/outlook.json
Adding code snippet example of the new sendAsync API to send message and appointments
> Adding code snippet example of the new sendAsync API

- playlists-prod/excel.yaml
- playlists/excel.yaml
- samples/excel/16-custom-functions/custom-enum-function.yaml
- samples/excel/16-custom-functions/custom-enum.yaml
- view-prod/excel.json
- view/excel.json
Add sample for using custom enum in custom function
> [Excel] (Custom Functions) Sample for using custom enum in custom function

- config/helpers.ts
- config/status.ts
- package.json
Running npm start would produce ANSI characters in the terminal, making running subsequent operations awkward. This PR removes the offending node-status dependency. 
I'm open to opinions on the terminal output.
> [admin] Remove garbage characters in the terminal
