- config/build.ts
- config/deploy.ts
- config/helpers.ts
Adds branch specific deployments to script-lab-samples.
@Zlatkovsky: things to do after you approve,
1. Make the repo public
2. In [Travis Config](https://travis-ci.com/OfficeDev/script-lab-samples/settings)
- delete `GH_BRANCH`
- change `GH_ACCOUNT` to officedev
- change `GH_REPO` to the final repo name
3. Update `env.config.js` on the main `script-lab` repo to pick from the right urls based on environment
> Changes to enable branch specific deployments

- samples/fabric/insert-form-data.yaml
Merging Fabric sample that was lost from previous check-in.
> Fabric sample check-in

- playlists/excel.yaml
- samples/excel/20-scenarios/report-generation.yaml
- samples/excel/30-range/working-with-dates.yaml
- samples/excel/70-events/selection-changed.yaml
* moment-msdate reference to 0.2.2, to fix error thrown on console 
https://github.com/markitondemand/moment-msdate/pull/10#issuecomment-302139249
* add try/catch to selection-changed
* remove custom notification from report-generation; instead use helper one instead.
> Small tweaks to existing snippets

- README.md
- playlists/excel.yaml
- samples/excel/06-named-item/create-and-remove-named-item.yaml
> README edits; added new code snippet for removing named items

- README.md
Nothing more, only added
to show some color.
> doc: code style

- samples/excel/01-basics/basic-api-call.yaml
- samples/excel/20-scenarios/report-generation.yaml
- samples/excel/default.yaml
- samples/onenote/default.yaml
- samples/word/01-basics/basic-api-call.yaml
- samples/word/default.yaml
Simplifying the try/catch pattern to remove a bunch of the repeated-over-and-over-again blocks of code.  We've had an email discussion about it with Jakob & co a month or two ago, and I discussed with Reeza and Ricky as well.
Looks like the diff in GitHub isn't particularly clean as to what is happening.  But here is a diff in VS Code:
> Added a simplified try/catch pattern to a few of the samples.

- playlists/excel.yaml
- samples/excel/30-range/test-for-used-range.yaml
Trying again to make a PR that does not include commits from earlier, not-yet-accepted PRs.
> snippet showing getUsedRangeOrNullObject

- playlists/excel.yaml
- playlists/powerpoint.yaml
- samples/excel/01-basics/basic-api-call.yaml
- samples/excel/20-scenarios/report-generation.yaml
- samples/excel/45-named-item/create-and-use-named-item-for-range.yaml
- samples/excel/default.yaml
- samples/onenote/default.yaml
- samples/word/01-basics/basic-api-call.yaml
- samples/word/default.yaml
This snippet went through 2 rounds of review from MichaelZ as part of a different PR that was cancelled.
> snippet for creating and using named range

- playlists/excel.yaml
- samples/excel/70-events/data-changed.yaml
> Take 2: snippet for range data-changed event handler

- playlists/excel.yaml
- samples/excel/35-worksheet/reference-worksheets-by-relative-position.yaml
Specifically: sheet.getNext, sheet.getPrevious, sheetCollection.getFirst, and sheetCollection.getLast.
> snippet to show worksheet relative-positioning APIs

- README.md
- config/build.ts
- package.json
- playlists/excel.yaml
- samples/excel/89-preview-apis/gridlines.yaml
- view/excel.json
Updated build.ts to add support for Preview APIs and to implement special casing for specific snippet Group Names; created new "Preview APIs" group for Excel; added new snippet (gridlines) to the "Preview APIs" group in Excel.
> Add support for Preview APIs

- playlists/excel.yaml
- samples/excel/89-preview-apis/gridlines.yaml
- samples/excel/89-preview-apis/range-text-orientation.yaml
- view/excel.json
Add new snippet that shows how to get and set text orientation within a range; edit worksheet-gridlines snippet to remove log statements.
> New snippet for  get/set text orientation within a range

- playlists/excel.yaml
- samples/excel/89-preview-apis/chart-axis.yaml
- samples/excel/89-preview-apis/chart-series.yaml
- samples/excel/89-preview-apis/chart-trendlines.yaml
- samples/excel/89-preview-apis/range-hyperlink.yaml
- samples/excel/89-preview-apis/range-text-orientation.yaml
- samples/excel/89-preview-apis/worksheet-freeze-panes.yaml
- samples/excel/89-preview-apis/worksheet-gridlines.yaml
- samples/excel/89-preview-apis/worksheet-tab-color.yaml
- view/excel.json
Already gone through code review.
> Shows how to get, set, and remove axis unit, title, and label in a chart.

- samples/excel/89-preview-apis/range-hyperlink.yaml
(Updated snippet per Sudhi's feedback.)
> Update range-hyperlink snippet

- samples/excel/89-preview-apis/chart-axis.yaml
- samples/excel/89-preview-apis/chart-legend.yaml
- samples/excel/89-preview-apis/chart-point.yaml
- samples/excel/89-preview-apis/chart-trendlines.yaml
- samples/excel/89-preview-apis/document-properties.yaml
- samples/excel/89-preview-apis/range-hyperlink.yaml
- samples/excel/89-preview-apis/range-text-orientation.yaml
- samples/excel/89-preview-apis/worksheet-freeze-panes.yaml
- samples/excel/89-preview-apis/worksheet-gridlines.yaml
- samples/excel/89-preview-apis/worksheet-tab-color.yaml
Re-ordered the list Libraries for each snippet, per Michael's recent suggestion. Also made a few (very) minor updates to the newly added Document Properties snippet, for clarity.
> Update Libraries for each snippet in the Preview APIs folder

- samples/word/01-basics/basic-doc-assembly.yaml
- samples/word/01-basics/insert-and-get-pictures.yaml
- samples/word/01-basics/insert-formatted-text.yaml
- samples/word/01-basics/insert-header.yaml
- samples/word/01-basics/insert-line-and-page-breaks.yaml
- samples/word/01-basics/search.yaml
- samples/word/02-paragraphs/get-paragraph-on-insertion-point.yaml
- samples/word/02-paragraphs/insert-in-different-locations.yaml
- samples/word/02-paragraphs/paragraph-properties.yaml
- samples/word/03-content-controls/insert-and-change-content-controls.yaml
- samples/word/04-range/scroll-to-range.yaml
- samples/word/04-range/split-words-of-first-paragraph.yaml
- samples/word/05-tables/table-cell-access.yaml
- samples/word/06-lists/insert-list.yaml
- samples/word/07-custom-properties/get-built-in-properties.yaml
- samples/word/07-custom-properties/read-write-custom-document-properties.yaml
Went through all the plain JS files and added TypeScript versions.
> Changing to Typescript

- samples/excel/70-events/data-changed.yaml
The docs don't do a great job explaining how to use this to full effect, and because the current sample doesn't even include the eventArgs argument, a user doesn't get a sense of how to interact with it.
> Add eventArgs example to Excel data changed sample

- playlists/word.yaml
- samples/word/50-preview-apis/multiple-property-set.yaml
- view/word.json
> Fix issues with multiple-property-set Word snippet

- samples/excel/89-preview-apis/pivot-table-create-and-modify.yaml
- samples/excel/89-preview-apis/pivot-table-filters-and-summaries.yaml
Adding a snippet to show how to interact with a pivot table to change the aggregate function, add a filter, and extract data from the table.
Also cleaning up the previous pivot sample.
> Pivot filtering and data samples

- samples/excel/89-preview-apis/events-disable-events.yaml
This sample shows how to turn on and off events.
My intention is to make this part of a larger sample once calculation toggling goes online. Hence why there's more code and data here than absolutely necessary.
> Event toggling snippet

- samples/excel/89-preview-apis/range-copyfrom.yaml
A sample showcasing Range.copyFrom(), aka copy and paste.
> Copy and paste sample

- playlists/excel.yaml
- samples/excel/89-preview-apis/pivottable-calculations.yaml
- samples/excel/89-preview-apis/pivottable-create-and-modify.yaml
- samples/excel/89-preview-apis/pivottable-filters-and-summaries.yaml
- view/excel.json
A snippet demonstrating the showAs functionality of the PivotTable API. Also cleaning up a couple old description mistakes.
> Adding a showAs PivotTable sample

- playlists/excel.yaml
- samples/excel/89-preview-apis/range-areas.yaml
The gist is here: https://gist.github.com/Rick-Kirkham/9d5aaecf0fc444fe58ea8c93ceba7669
> expanded the RangeAreas snippet

- samples/excel/89-preview-apis/chart-formatting.yaml
This snippet was giving an InvalidOperation error. Tested in Script Lab and it works fine now.
Here's the gist for convenience. https://gist.github.com/3e3529ad58f4908093b6aed7cb8f440e
> Fixing snippet bug

- samples/excel/50-chart/chart-axis-formatting.yaml
Removing duplicate functions this snippet.
> Duplicate functions

- playlists/excel.yaml
- samples/excel/85-preview-apis/performance-optimization.yaml
- samples/excel/85-preview-apis/range-remove-duplicates.yaml
- samples/excel/85-preview-apis/tetrominos.yaml
- samples/excel/85-preview-apis/worksheet-page-layout.yaml
- view/excel.json
This snippet showcases some page layout and print setting features coming in Excel 1.9.
> [excel] (Worksheet) Page layout snippet

- playlists/excel.yaml
- samples/excel/85-preview-apis/performance-optimization.yaml
- samples/excel/85-preview-apis/range-remove-duplicates.yaml
- samples/excel/85-preview-apis/shape-move-and-order.yaml
- samples/excel/85-preview-apis/shapes-images.yaml
- samples/excel/85-preview-apis/tetrominos.yaml
- samples/excel/85-preview-apis/workbook-insert-external-worksheets.yaml
- samples/excel/85-preview-apis/workbook-save-and-close.yaml
- samples/excel/85-preview-apis/worksheet-page-layout.yaml
- view/excel.json
This sample shows some of the unique APIs for image-based shapes.
> (excel) [Shape] Sample for shapes using images

- config/build.ts
- samples/outlook/01-compose-basics/get-item-subject.yaml
- samples/outlook/01-compose-basics/get-selected-text.yaml
- samples/outlook/01-compose-basics/set-selected-text.yaml
- yarn.lock
Merging in @annich-MS 's changes.  They don't impact anything for Excel/Word, it's only for Outlook.
> Master => Prod

- README.md
Feedback from PR https://github.com/OfficeDev/office-js-snippets/pull/283.
> Update readme based on feedback

- package-lock.json
- playlists/excel.yaml
- samples/excel/16-custom-functions/basic-function.yaml
- samples/excel/16-custom-functions/streaming-function.yaml
- samples/excel/16-custom-functions/volatile-function.yaml
- view/excel.json
This just shows how to write a basic custom function. In this case it calculates the volume of a sphere.
> added basic custom function

- playlists/excel.yaml
- samples/excel/85-preview-apis/comment-mentions.yaml
- samples/excel/85-preview-apis/comment-resolution.yaml
- samples/excel/85-preview-apis/workbook-calculation.yaml
- samples/excel/85-preview-apis/workbook-insert-external-worksheets.yaml
- samples/excel/85-preview-apis/workbook-save-and-close.yaml
- view/excel.json
This snippet was originally designed to highlight the new `WorksheetCalculatedEventArgs.address` property, but seemed like a good place to showcase more related APIs.
> [excel] (Calculation APIs) Workbook calculation snippet

- playlists/outlook.yaml
- samples/outlook/99-preview-apis/work-with-client-signatures.yaml
- samples/outlook/preview-apis-signature/work-with-client-signatures.yaml
- view/outlook.json
Adding samples in ScriptLab for the Signature APIs including:
1. isClientSignatureEnabledAsync
2. disableClientSignatureAsync
3. getComposeTypeAsync
4. setSignatureAsync
> Adding Signature API Samples

- samples/excel/10-chart/chart-bubble-chart.yaml
- samples/excel/30-events/events-comment-event-handler.yaml
- snippet-extractor-output/snippets.yaml
Found in https://github.com/OfficeDev/office-js-docs-reference/pull/795
> [admin] (Typo) Fixing recent snippet typos

- yarn.lock
This should address the security alerts.
> [admin] Updating yarn.lock

- samples/excel/42-range/precedents.yaml
Running yarn start as a separate PR because I forgot to run it with PR #579.
> [Excel] (Range) Add accidentally deleted tryCatch + run yarn start

- samples/excel/50-workbook/create-workbook.yaml
- samples/powerpoint/basics/create-presentation.yaml
- samples/powerpoint/slide-management/insert-slides.yaml
Just a something I noticed doing unrelated work. Figured this version localizes and sounds better.
> [Excel, PowerPoint] Changing the term "strip off" to "remove"

- samples/excel/90-scenarios/working-with-dates.yaml
Also removing some unnecessary white space.
> [excel] (Dates) Removing stray code ticks

- playlists-prod/word.yaml
- playlists/word.yaml
- samples/word/99-preview-apis/content-control-ondeleted-event.yaml
- snippet-extractor-output/snippets.yaml
* [Word] (content control) Add how to deregister onDeleted event (#605)
* Update based on feedback
> [admin] main -> prod

- samples/excel/42-range/range-find.yaml
- snippet-extractor-output/snippets.yaml
> [Excel] (Range) Fix bug in find snippet

- samples/word/50-document/manage-change-tracking.yaml
- samples/word/50-document/manage-comments.yaml
- samples/word/50-document/manage-footnotes.yaml
- snippet-extractor-output/snippets.yaml
> [Word] (online) Check for WordApiOnline 1.1 requirement set

- playlists-prod/outlook.yaml
- playlists/outlook.yaml
- samples/outlook/85-tokens-and-service-calls/get-icaluid-as-attendee.yaml
- view-prod/outlook.json
- view/outlook.json
> [Outlook] (EWS) Gets an appointment's iCalUId as an attendee

- samples/outlook/20-item-body/append-text-on-send.yaml
> [Outlook] (appendOnSendAsync) Add manifest note and walkthrough link to snippet

- samples/excel/20-data-types/data-types-entity-values.yaml
[Internal work item](https://office.visualstudio.com/OC/_workitems/edit/6090249).
> [Excel] (Data types) Add icons enum to entity sample

- samples/outlook/99-preview-apis/prepend-text-on-send.yaml
Related PR: https://github.com/OfficeDev/office-js-docs-pr/pull/3817
> [Outlook] (prepend-on-send) Add link to conceptual article from Script Lab snippet

- playlists-prod/outlook.yaml
- playlists/outlook.yaml
- samples/outlook/70-mime-headers/get-internet-headers-message-read.yaml
- samples/outlook/70-mime-headers/manage-custom-internet-headers-message-compose.yaml
- snippet-extractor-output/snippets.yaml
Removes "x-" from the internet header code snippets as this isn't a requirement and isn't enforced by the API.
> [Outlook] (internet headers) Correct snippets

- playlists-prod/word.yaml
- playlists/word.yaml
- samples/word/50-document/manage-annotations.yaml
- view-prod/word.json
- view/word.json
I'll add metadata mappings later
> [Word] (writing assistance) Add snippet on managing annotations

- SECURITY.md
- samples/excel/42-range/range-hyperlink.yaml
- snippet-extractor-output/snippets.yaml
This PR removes militaristic language from these docs.
> [all] (Language) Adjust language for new security guidelines

- playlists-prod/word.yaml
- playlists/word.yaml
- samples/word/50-document/manage-comments.yaml
- samples/word/99-preview-apis/manage-comments.yaml
- snippet-extractor-output/snippets.yaml
- view-prod/word.json
- view/word.json
Will add snippet mappings in subsequent PR
> [Word] (comments) Expand snippet to include event handling

- samples/outlook/20-item-body/prepend-text-on-send.yaml
- samples/outlook/20-item-body/prepend-text-to-item-body.yaml
- samples/outlook/20-item-body/replace-selected-text.yaml
- snippet-extractor-output/snippets.yaml
Calls the `toString` method on values submitted by users.
> [Outlook] Add toString method

- samples/outlook/35-notifications/add-getall-remove.yaml
Related PRs:
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70168
- https://github.com/OfficeDev/office-js-docs-pr/pull/4693
- https://github.com/OfficeDev/office-js-docs-reference/pull/2009
- https://github.com/OfficeDev/Office-Add-in-samples/pull/820
> [Outlook] (new Outlook on Windows) Remove preview string

- playlists-prod/outlook.yaml
- playlists/outlook.yaml
- samples/outlook/40-attachments/attachments-compose.yaml
- samples/outlook/65-delegates-and-shared-folders/get-shared-properties.yaml
Updates minimum supported requirement sets based on recent changes.
- [Implement shared folders and shared mailbox scenarios in an Outlook add-in](https://learn.microsoft.com/office/dev/add-ins/outlook/delegate-access#configure-the-manifest)
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71110
> [Outlook] Update minimum supported requirement sets

- samples/word/50-document/insert-external-document.yaml
- snippet-extractor-output/snippets.yaml
Fixes https://github.com/OfficeDev/office-js/issues/5005
> [Word] (insert external doc) Check for platform-specific reqt. set

- samples/excel/42-range/range-get-range-edge.yaml
- samples/outlook/90-other-item-apis/get-message-properties.yaml
- samples/powerpoint/slide-management/insert-slides.yaml
Making adjustments to what's displayed in the Run pane.
Before:
After:
> [all hosts] Use kbd for keys and keyboard combinations

- playlists-prod/word.yaml
- playlists/word.yaml
- samples/word/99-preview-apis/insert-and-change-content-controls.yaml
- samples/word/99-preview-apis/manage-comments.yaml
- snippet-extractor-output/snippets.yaml
Also, for sample with GA version, indicate which features are currently in preview.
> [Word] (preview) Update to next set

- samples/outlook/40-attachments/get-attachment-content.yaml
- snippet-extractor-output/snippets.yaml
Related to https://github.com/OfficeDev/office-js-docs-reference/pull/2279.
> [Outlook] (attachments) Update snippet for getAttachmentContentAsync method

- playlists-prod/excel.yaml
- playlists/excel.yaml
- samples/excel/16-custom-functions/custom-enum.yaml
This PR tweaks a sample submitted by a PM partner, to add a code comment, adjust grammar, and match formatting.
Original submission: https://github.com/OfficeDev/office-js-snippets/pull/988
> [Excel] (Custom functions) Minor changes to custom enum sample

- .gitignore
- playlists-prod/excel.yaml
- playlists/excel.yaml
- samples/excel/20-data-types/data-types-basic-types.yaml
- view-prod/excel.json
- view/excel.json
This snippet shows how to add metadata to basic types and work with those types. 
This PR is ready to merge. Planning to update excel.xlsx  to generate ref docs samples in a subsequent PR.
> [Excel] (Data types) Add basic types with metadata snippet
